#!/usr/bin/env python3
"""seed_demo.py — generate clearly-labeled SAMPLE data for the board.

Everything here is synthetic (fictional companies, deterministic RNG seed)
so contributors can see a full board in 30 seconds without connecting Gmail.
The public demo at /docs is built from this via `python -m engine.cli demo`.
"""
import os
import random
import sys
from datetime import date, timedelta

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from engine import config as config_mod  # noqa: E402
from engine import store as store_mod  # noqa: E402

COMPANIES = [
    "Northwind Tech", "Acme Analytics", "Lumen Financial", "Vertex Labs",
    "Cobalt Systems", "Meridian Bank", "Helix AI", "Atlas Logistics",
    "Orion Health", "Solstice Media", "Granite Capital", "Pinnacle Retail",
    "Beacon Software", "Cascade Energy", "Summit Consulting", "Vega Gaming",
    "Quill Fintech", "Harbor Data", "Nimbus Cloud", "Ironwood Industrial",
    "Kestrel Strategy", "Onyx Payments", "Polaris Research", "Sage Ventures",
    "Tidal Commerce", "Umbra Security", "Willow HealthTech", "Zephyr Mobility",
    "Drift Marketing", "Ember Robotics", "Cedar Capital", "Flint Mobility",
    "Garnet Group", "Indigo Insights", "Juniper Bank", "Koda Cloud",
]

TITLES = [
    "Data Analyst", "Senior Data Analyst", "Business Intelligence Analyst",
    "Analytics Manager", "Data Scientist", "Insights Analyst",
    "Product Manager", "Senior Product Manager", "Product Analyst",
    "Software Engineer", "Backend Developer", "Full Stack Developer",
    "Operations Analyst", "Strategy Associate", "Business Operations Specialist",
    "Process Analyst", "Risk Analyst", "Financial Analyst", "Credit Analyst",
    "Consultant", "Business Consultant", "Growth Marketing Manager",
    "Marketing Analyst",
]

SOURCES = ["Greenhouse", "Lever", "Workday", "Ashby", "LinkedIn", "Indeed",
           "Direct", "SmartRecruiters", "iCIMS"]

# (stage, weight) — a plausible funnel
STAGES = [("Applied", 42), ("Assessment", 8), ("Phone Screen", 10),
          ("Interview", 12), ("Round 2", 6), ("Round 3", 3), ("Final Round", 4),
          ("Offer", 3), ("Rejected", 12)]

FIRST = ["Ava", "Liam", "Maya", "Noah", "Priya", "Lucas", "Sofia", "Ethan",
         "Zara", "Owen", "Nina", "Kai"]
LAST = ["Patel", "Kim", "Garcia", "Nguyen", "Smith", "Chen", "Khan", "Ali",
        "Brown", "Singh", "Lee", "Dube"]
ROLES = ["Recruiter", "Talent Partner", "Hiring Manager", "Team Lead"]


def _pick_stage(rng):
    total = sum(w for _, w in STAGES)
    x = rng.uniform(0, total)
    for stage, w in STAGES:
        x -= w
        if x <= 0:
            return stage
    return "Applied"


def seed(st, cfg, clear=False, rng_seed=42):
    """Seed the store with synthetic sample data. Returns app count."""
    rng = random.Random(rng_seed)
    if clear:
        for t in ("applications", "interviews", "contacts", "leads"):
            st.conn.execute(f"DELETE FROM {t}")
    st.seed_templates(cfg.get("templates", []))
    today = date.today()

    n_apps = 0
    advanced = []
    for i in range(92):
        company = COMPANIES[i % len(COMPANIES)]
        title = rng.choice(TITLES)
        # de-dup titles per company so keys stay unique
        if i >= len(COMPANIES):
            title = f"{title} ({i // len(COMPANIES) + 1})"
        stage = _pick_stage(rng)
        days_ago = int(rng.betavariate(2, 5) * 150)
        d = (today - timedelta(days=days_ago)).isoformat()
        interview = stage not in ("Applied", "Rejected")
        action, aid = st.upsert_application({
            "thread_id": f"sample-thread-{i:03d}",
            "company": company, "title": title, "url": "",
            "stage": stage, "date_applied": d,
            "source": rng.choice(SOURCES), "reply": True,
            "interview": interview,
            "flag": rng.random() < 0.04,
            "notes": "Sample data — generated by seed_demo.py",
        }, cfg)
        if action == "added":
            n_apps += 1
        if interview and stage != "Offer":
            advanced.append((company, title, d, stage))

    # interviews for advanced applications
    for j, (company, title, applied, stage) in enumerate(advanced):
        rounds = {"Assessment": ["Online Assessment"],
                  "Phone Screen": ["Recruiter Screen"],
                  "Interview": ["Recruiter Screen", "Round 1"],
                  "Round 2": ["Recruiter Screen", "Round 1", "Round 2"],
                  "Round 3": ["Round 1", "Round 2", "Round 3"],
                  "Final Round": ["Round 1", "Round 2", "Final Round"]}[stage]
        base = date.fromisoformat(applied)
        for k, rnd in enumerate(rounds):
            d = (base + timedelta(days=4 + 6 * k + rng.randint(0, 3))).isoformat()
            if date.fromisoformat(d) > today:
                continue
            st.add_interview({
                "thread_id": f"sample-iv-{j:03d}-{k}",
                "company": company, "title": title, "date": d, "round": rnd,
                "interviewer": "Talent Team",
                "details": "Sample interview — generated by seed_demo.py",
            })

    # contacts
    for i in range(12):
        company = rng.choice(COMPANIES)
        d = (today - timedelta(days=rng.randint(2, 60))).isoformat()
        st.add_contact({
            "name": f"{rng.choice(FIRST)} {rng.choice(LAST)}",
            "title": rng.choice(ROLES), "company": company,
            "email": f"contact{i + 1}@example.com", "phone": "",
            "warmth": rng.choice(["hot", "warm", "warm", "warm"]),
            "last_touch": d,
            "context": "Sample contact — generated by seed_demo.py",
            "linkedin": "",
        })

    # leads
    for i in range(14):
        d = (today - timedelta(days=rng.randint(0, 9))).isoformat()
        st.add_lead({
            "company": rng.choice(COMPANIES), "title": rng.choice(TITLES),
            "source": rng.choice(["LinkedIn", "Indeed"]),
            "date": d, "url": "",
        })

    st.conn.commit()
    return n_apps


def main():
    cfg = config_mod.load()
    with store_mod.Store() as st:
        n = seed(st, cfg)
    print(f"seeded {n} sample applications → {store_mod.DEFAULT_DB}")


if __name__ == "__main__":
    main()
